builds:
  - main: ./cmd/redis-template/main.go
    binary: redis-template
    goos:
      - linux
    goarch:
      - amd64
    flags: -a -tags netgo
    ldflags: -w
    env:
      - CGO_ENABLED=1
dockers:
  - image: robbert229/redis-template
    goos: linux
    goarch: amd64
    dockerfile: ./Dockerfile
    binary: redis-template
    tag_templates:
      - "{{ .Version }}"
      - latest
env_files:
  github_token: ./.github_token