builds:
  - main: ./cmd/redis-template/main.go
    binary: drum-roll
    goos:
      - linux
    goarch:
      - amd64
    flags: -a -tags netgo
    ldflags: -w
    env:
      - CGO_ENABLED=1
env_files:
  github_token: ./.github_token